# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiller" do
  version "0.10.3"

  on_macos do
    on_arm do
      sha256 "2b7eb8aeecfa447af8ca5e767472d218ad28a21d5f58571443b04e5fd2be7423"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "022265b88ebba4c79f8552fbff5dba1830ef3134f1570bea334876d127ed67c7"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7099baa19ef95ef0838468063bd81ead906157ec8115a9140c2f7607ca07e456"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb2652f47db87a4fca9b473f5f62cc1dcb7debb8b8d7e9d0dcad5d04ecfbd662"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tiller"
  desc "An opinionated SDLC workflow tool for humans and AI coding agents working together"
  homepage "https://github.com/madeintandem/tiller"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiller"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiller"]
    end
  end

  # No zap stanza required
end
