# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiller" do
  version "0.10.2"

  on_macos do
    on_arm do
      sha256 "701539a33aa9324b7cbfdbbf256dd66a7c2feec3f9167dcca77127c0f003bc24"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4dc1225e82a25dfa4c4295f9076073a79d64d8de662cd5e83add58a595a247a"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74a2b4a28240d769f7cda8ef35e9bc7a727299c3acdc8c89bb35a64613f117dc"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48fd6d22c815dcf7351b20c8ffbd1fe11d8147f310a279842086043a758f3660"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tiller"
  desc "An opinionated SDLC workflow tool for humans and AI coding agents working together"
  homepage "https://github.com/madeintandem/tiller"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiller"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiller"]
    end
  end

  # No zap stanza required
end
