# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiller" do
  version "0.11.3"

  on_macos do
    on_arm do
      sha256 "f64d566a9f1e70f210bf446491f2a4254af13c605ef679bdaece58308a954cfa"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b7bcb5b685fe776631929e334e99740b46e390e7576562605edbeb74520a814"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1563b4ef0ca2bf6257217d9744e5746d25c026133f43b2eb2fe55776947b86ae"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cec4ea7e465fc05d3f7d5feca0962d06de9444791053c59716b12ee51c26f2a"
      url "https://github.com/madeintandem/tiller/releases/download/v#{version}/tiller_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tiller"
  desc "An opinionated SDLC workflow tool for humans and AI coding agents working together"
  homepage "https://github.com/madeintandem/tiller"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiller"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiller"]
    end
  end

  # No zap stanza required
end
